version: '3'
services:
  ebiznes:
    build: .
    ports:
      - 9000:9000
      - 3000:3000
    volumes:
      - .:/home/pati/Documents/sem8/ebiznes/play-shop/shop
    working_dir: /home/patdem/apps/shop
    command: bash -c "sbt run"